# Replace repo url with the repository url for your Jumpstart Pro application
services:
  - type: web
    repo: https://github.com/reneklacan/comfy
    name: comfy-web
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s
    region: frankfurt
    plan: free
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: comfy-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: comfy-redis
          property: connectionString

  - type: redis
    name: comfy-redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: volatile-lru
    region: frankfurt

databases:
  - name: comfy-postgres
    ipAllowList: []
    region: frankfurt
    plan: free

