--- !ruby/object:Jumpstart::Configuration
application_name: Comfy
business_name: Comfy
business_address: ''
domain: example.com
default_from_email: Jumpstart <support@example.com>
support_email: rene.klacan@gmail.com
background_job_processor: sidekiq
email_provider: ''
personal_accounts: true
solargraph: true
register_with_account: false
apns: false
fcm: false
collect_billing_address: false
